force-app/main/default/objects/Certifications__c/Certifications__c.object-meta.xml
<CustomObject>
    <description>A custom object that represents a users technology certifications.</description>
    <label>Certification</label>
    <nameField>
        <label>Certifications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <description>The education records will display in your resume through a lookup relationship.</description>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>A custom object that represents an individuals job experience.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field links an Experience record to a Resume.</description>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <description>A custom object that represents an individuals base resume information.</description>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ResumeBuilderController.cls
public with sharing class ResumeBuilderController {

    @AuraEnabled
    public static String getResume(){
        try {
            Resume__c resume = [SELECT Id, (SELECT Id FROM Experiences__r),(SELECT Id FROM Education__r), (SELECT Id, Certification__c FROM Resume_Certifications__r) FROM Resume__c LIMIT 1];
            List<Id> certIds = new List<Id>();
            for(Resume_Certification__c resumeCert : resume.Resume_Certifications__r){
                certIds.add(resumeCert.Certification__c);
            }
            List<Certifications__c> certs = [SELECT Id FROM Certifications__c WHERE Id IN: certIds];
            ResumeDetails resumeDetails = new ResumeDetails(resume,certs);
            system.debug('This was called' + JSON.serializePretty(resumeDetails));
            return JSON.serialize(resumeDetails);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class ResumeDetails{
        @AuraEnabled
        public Resume__c resume;
        @AuraEnabled
        public List<Certifications__c> certifications;
        @AuraEnabled
        public List<Education__c> education;
        @AuraEnabled
        public List<Experience__c> experiences;
        public ResumeDetails(Resume__c resume, List<Certifications__c> certifications) {
                this.certifications = certifications;
                this.resume = resume;
                this.education = resume.Education__r;
                this.experiences = resume.Experiences__r;
        }
    }
}